class DomainException(Exception): ...


class RoleMismatch(DomainException): ...


class RoleNotFoundException(DomainException): ...


class NoTokenProvidedException(DomainException): ...


class RoleRequiredException(DomainException): ...


class InvalidUsernameException(DomainException): ...


class UsernameAlreadyExistsException(DomainException): ...


class NotAuthenticatedException(DomainException): ...


class TokenTypeMismatchException(DomainException): ...


class UserNotFoundException(DomainException): ...


class TokenInvalidatedException(DomainException): ...


class UserDisabledException(DomainException): ...


class UnauthorizedException(DomainException): ...


class InvalidPasswordException(DomainException): ...


class PasswordConfirmationMissmatchException(DomainException): ...


class InvalidTokenException(DomainException): ...
