"""added settings

Revision ID: af29fd36901c
Revises: b1d9c58e2c6e
Create Date: 2025-12-22 14:36:55.556870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af29fd36901c'
down_revision: Union[str, Sequence[str], None] = 'b1d9c58e2c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settings',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('key'),
    )
    op.create_unique_constraint('uq_roles_id', 'roles', ['id'])
    op.create_unique_constraint('uq_users_id', 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_id', 'users', type_='unique')
    op.drop_constraint('uq_roles_id', 'roles', type_='unique')
    op.drop_table('settings')
    # ### end Alembic commands ###
