"""fill db

Revision ID: e1e58db5bd29
Revises: af29fd36901c
Create Date: 2025-12-22 14:38:36.831261

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from src.domain.enums import RoleEnum
from src.infrastructure.models import generate_id

# revision identifiers, used by Alembic.
revision: str = 'e1e58db5bd29'
down_revision: Union[str, Sequence[str], None] = 'af29fd36901c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_settings_id', 'settings', ['id'])
    op.bulk_insert(
        sa.table(
            'roles',
            sa.column('id', sa.UUID),
            sa.column('name', sa.String),
        ),
        [
            {'id': role_id, 'name': role_name}
            for role_name, role_id in RoleEnum.get_id_mapper().items()
        ],
    )
    op.bulk_insert(
        sa.table(
            'settings',
            sa.column('id', sa.UUID),
            sa.column('key', sa.String),
            sa.column('value', sa.String),
        ),
        [{'id': generate_id(), 'key': 'is_reg_open', 'value': False}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_settings_id', 'settings', type_='unique')
    op.execute('DELETE FROM settings WHERE key="is_reg_open"')
    op.execute('DELETE FROM roles')
    # ### end Alembic commands ###
