"""init

Revision ID: 8a05d7004f3e
Revises:
Create Date: 2025-12-20 23:42:57.893750

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8a05d7004f3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
